classDiagram

namespace hexrotcomm {
  class CommandTelemetryClient
}

namespace guitool {
  class ControlTabs
  class TabTemplate
}

namespace tab {
  class TabSettings
}

TabTemplate <|-- TabSettings

MainWindow *-- Model
MainWindow *-- ControlTabs
MainWindow *-- ControlPanel
MainWindow *-- TabSettings

Model *-- CommandTelemetryClient
Model *-- Status
Model *-- MockController
Model *-- SignalState : emit()
Model *-- SignalApplicationStatus : emit()
Model *-- SignalPositionVelocity : emit()
Model *-- SignalPower : emit()
Model *-- SignalControl : emit()
Model *-- SignalDrive : emit()
Model *-- SignalConfig : emit()
Model ..> Config

ControlPanel *-- Model
ControlPanel --> SignalState : connect()
ControlPanel --> SignalPositionVelocity : connect()
ControlPanel --> SignalConfig : connect()

TabSettings *-- Model

ControlTabs "1" *-- "5" TabTemplate
