classDiagram

namespace guitool {
  class TabTemplate
}

namespace rotgui {
  class Model
  class SignalApplicationStatus
  class SignalControl
  class SignalPositionVelocity
  class SignalPower
}

Model *-- SignalApplicationStatus : emit()
Model *-- SignalControl : emit()
Model *-- SignalPositionVelocity : emit()
Model *-- SignalPower : emit()

TabTemplate <|-- TabTelemetry

TabTelemetry *-- Model
TabTelemetry --> SignalApplicationStatus : connect()
TabTelemetry --> SignalControl : connect()
TabTelemetry --> SignalPositionVelocity : connect()
TabTelemetry --> SignalPower : connect()
