classDiagram

namespace guitool {
  class TabTemplate
}

namespace rotgui {
  class Model
  class SignalPower
}

Model *-- SignalPower : emit()

TabTemplate <|-- TabPower

TabPower *-- Model
TabPower --> SignalPower : connect()
