classDiagram

namespace guitool {
  class TabTemplate
}

namespace rotgui {
  class Model
  class SignalDrive
}

Model *-- SignalDrive : emit()

TabTemplate <|-- TabDriveStatus

TabDriveStatus *-- Model
TabDriveStatus --> SignalDrive : connect()
