classDiagram

namespace guitool {
  class TabTemplate
}

TabTemplate <|-- TabDriveStatus
TabTemplate <|-- TabPosition
TabTemplate <|-- TabSettings
TabTemplate <|-- TabTelemetry
TabTemplate <|-- TabPower
TabTemplate <|-- TabConfig
