classDiagram

namespace guitool {
  class TabTemplate
}

namespace rotgui {
  class Model
  class SignalPositionVelocity
}

Model *-- SignalPositionVelocity : emit()

TabTemplate <|-- TabPosition

TabPosition *-- Model
TabPosition --> SignalPositionVelocity : connect()
