classDiagram

namespace guitool {
  class TabTemplate
}

namespace rotgui {
  class Model
  class Config
  class SignalApplicationStatus
  class SignalConfig
  class SignalControl
  class SignalPositionVelocity
}

Model ..> Config
Model *-- SignalApplicationStatus : emit()
Model *-- SignalConfig : emit()
Model *-- SignalControl : emit()
Model *-- SignalPositionVelocity : emit()

TabTemplate <|-- TabTelemetry

TabTelemetry *-- Model
TabTelemetry ..> Config
TabTelemetry --> SignalApplicationStatus : connect()
TabTelemetry --> SignalConfig : connect()
TabTelemetry --> SignalControl : connect()
TabTelemetry --> SignalPositionVelocity : connect()
